name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

  security:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check vulnerabilities
        uses: snyk/actions/setup@v2
        with:
          version: 'latest'
      - name: Test for vulnerabilities
        run: snyk test

      - name: Run Trivy to scan container image
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: 'your-docker-image:tag'

  deploy:
    runs-on: ubuntu-latest
    needs: [build, security]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Deploying application..."
